/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangProjectsRouteImport } from './routes/$lang.projects'
import { Route as LangFaqRouteImport } from './routes/$lang.faq'
import { Route as LangDubaiResidencyPropertyRouteImport } from './routes/$lang.dubai-residency-property'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangBlogRouteImport } from './routes/$lang.blog'
import { Route as LangAboutRouteImport } from './routes/$lang.about'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangProjectsRoute = LangProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangDubaiResidencyPropertyRoute =
  LangDubaiResidencyPropertyRouteImport.update({
    id: '/dubai-residency-property',
    path: '/dubai-residency-property',
    getParentRoute: () => LangRoute,
  } as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogRoute = LangBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dubai-residency-property': typeof LangDubaiResidencyPropertyRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dubai-residency-property': typeof LangDubaiResidencyPropertyRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dubai-residency-property': typeof LangDubaiResidencyPropertyRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/dubai-residency-property'
    | '/$lang/faq'
    | '/$lang/projects'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/dubai-residency-property'
    | '/$lang/faq'
    | '/$lang/projects'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/dubai-residency-property'
    | '/$lang/faq'
    | '/$lang/projects'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/projects': {
      id: '/$lang/projects'
      path: '/projects'
      fullPath: '/$lang/projects'
      preLoaderRoute: typeof LangProjectsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/dubai-residency-property': {
      id: '/$lang/dubai-residency-property'
      path: '/dubai-residency-property'
      fullPath: '/$lang/dubai-residency-property'
      preLoaderRoute: typeof LangDubaiResidencyPropertyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog': {
      id: '/$lang/blog'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangBlogRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBlogRoute: typeof LangBlogRoute
  LangContactRoute: typeof LangContactRoute
  LangDubaiResidencyPropertyRoute: typeof LangDubaiResidencyPropertyRoute
  LangFaqRoute: typeof LangFaqRoute
  LangProjectsRoute: typeof LangProjectsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBlogRoute: LangBlogRoute,
  LangContactRoute: LangContactRoute,
  LangDubaiResidencyPropertyRoute: LangDubaiResidencyPropertyRoute,
  LangFaqRoute: LangFaqRoute,
  LangProjectsRoute: LangProjectsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
